name: docker build+test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Docker build
      run: docker build -t mrcieu/siblinggwas .
    - name: Docker run
      run: >
        docker run mrcieu/siblinggwas within-family -h
        docker run mrcieu/siblinggwas within-family-plots -h
